<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
	<name>cpp_pubsub</name>
	<version>0.0.0</version>
	<description>Examples of minimal publisher/subscriber using rclcpp</description>
<maintainer email="robinchovallurraju@gmail.com">Robin CR</maintainer>
<license>Apache License 2.0</license>
<depend>rclcpp</depend>
<depend>std_msgs</depend>
</package>